### ISSUE TITLE
Better way to glScissor

### ISSUE THREAD

**Issue by mchorse** [diesieben07/SevenCommons#2]
Hey there! I was writing scrolling pane for myself and stuck onto your code while searching for `minecraft forge` and `glScissor`.

So instead of figuring out the scale of the screen, you can determine first the ratios:

``` java
int rx = this.mc.displayWidth / this.width;
int ry = this.mc.displayHeight / this.height;
```

And then multiply your rect's x, y, width and height by those ratios:

``` java
int w = 200;
int h = 200;
int x = width/2 - w;
int y = 80;

GL11.glScissor(x * rx, this.mc.displayHeight - (y + h) * ry, w * rx, h * ry);
```

That is another simpler (and better) way to glScissor in minecraft's GUI.

P.S.: Maybe you're already figured out (since [this topic](http://www.minecraftforge.net/forum/index.php?topic=19948.0) is over two years old), but I'm gonna do it anyway, since the code hasn't changed.

**Comment by diesieben07** [comment]
Yes, I figured that out already, the master branch is ages old and not maintained.
Thanks though.
